### ISSUE TITLE
Wrong encoding of negative ScaledValue

### ISSUE THREAD

**Issue by andrepf** [mz-automation/lib60870.NET#11]
When a **ScaledValue** is created with a negative value, it's not encoded correctly to a byte array, so the returned value is invalid. Example code:

> // scaledValue.Value is 255 instead of -1
> var scaledValue = new ScaledValue(-1); 

The problem is located on file _ScaledValue.cs_, when the **Value/ShortValue** properties are set.

**Comment by mzillgith** [comment]
Thanks. Should be fixed now.
