### ISSUE TITLE
How to handle select-before-execute in a server?

### ISSUE THREAD

**Issue by gboor** [mz-automation/lib60870.NET#17]
As the title says; I'm just wondering if there is some sort of default stub for this that handles timeout etc., or if this is something that needs to be created from scratch.

I'm using the C# lib. If anyone has some examples of how to do this, that would be helpful too!

I previously posted this here; https://github.com/mz-automation/libiec61850/issues/278, but realized I had the wrong repo!

**Comment by mzillgith** [comment]
Your application has to handle this by checking the state of the select/execute flag.

This can be done by code like below in the AsduHandler callback:

```
SingleCommand sc = (SingleCommand)asdu.GetElement (0);

if (sc.Select)
{
    //select
}
else
{
    //execute
}
```

**Comment by gboor** [comment]
Thanks! I see this also made it into the example. I will close this ticket.
