### ISSUE TITLE
Talos Security Advisory for MZ Automation GmbH

### ISSUE THREAD

**Issue by CiscoTalos** [mz-automation/lib60870.NET#21]
Hello,
The Cisco Talos team found a security vulnerability affecting MZ Automation. As this is a sensitive security issue, this message is to request an email contact/maintainer handling and PGP key for further communication. If there's an option to mark this issue as private, we can place the details here.

For further information about the Cisco Vendor Vulnerability Reporting and Disclosure Policy please refer to this document which also links to our public PGP key. https://tools.cisco.com/security/center/resources/vendor_vulnerability_policy.html

Please CC vulndev@cisco.com on all correspondence related to this issue.

###Tested Versions
MZ Automation GmbH lib60870.NET 2.2.0

**Comment by mzillgith** [comment]
Hello,
If you found a bug that you don't want to publish the details here, please send your bug report to support@mz-automation.de
Thanks
