### ISSUE TITLE
Send Invalid Message to Master

### ISSUE THREAD

**Issue by yagizhanNY** [mz-automation/lib60870.NET#22]
How can we send invalid quality message for all information objects from same ASDU to master device?

```
QualityDescriptor qualityDescriptor = new QualityDescriptor();
qualityDescriptor.Invalid = true;
```

I can send information object with invalid quality description but I want to send invalid message to without change any value of information objects. Is it possible?

**Comment by mzillgith** [comment]
No. It's not possible. You need to change the information objects.
