### ISSUE TITLE
IEC104 Client Hangs On Connection.Close()

### ISSUE THREAD

**Issue by iman7107** [mz-automation/lib60870.NET#31]
Hi.
When I call Connection.Close(); method for IEC104 Client, the system runs into hang. in the server side shows that client disconnected. but my form freezes in client side. I have Traced the Close() method and freezing occurs after execute line **workerThread.Join();**.
How can I solve the problem.
Thanks.

**Comment by ibekaddour** [comment]
Hello,
Could you please provide more details about the issue, also you are running the client and server.
Thank you.

**Comment by iman7107** [comment]
Hi again.
I use **Axon Test** software as RTU(Server) IEC104 simulator. 
This is my **Connect** method body:
```
 con = new Connection(IPTextBox.Text, Convert.ToInt32(PortTextBox.Text));
            con.DebugOutput = true;
            con.SetASDUReceivedHandler(asduReceivedHandler, null);
            con.SetConnectionHandler(ConnectionHandler, null);
            try
            {
                con.Connect();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }

```
and I do something in ASDURecieveHandler.
everything is OK. But when I click on **Disconnect** Button my form run ino Hang.
This is my **Disconnect** method body:
```
     try
                {
                    con.Close();
                }
                catch (Exception ex)
                {
                    MessageBox.Show("Close Connection Error : " + Environment.NewLine + ex.ToString(), "Close Connection Error");
                }

```
-------------------------------------------
I changed my code and now my Disconnect method body is like this:
```
     try
                {
                    con.Cancel();
                    con.Close();
                }
                catch (Exception ex)
                {
                    MessageBox.Show("Close Connection Error : " + Environment.NewLine + ex.ToString(), "Close Connection Error");
                }

```
and now it is OK. Should I call con.Cancel() before con.Close() ? I saw Cancel method close the Socket and because of this, I called Cancel() method before Close(). Did I do correct way?

**Comment by juwiefer-btc** [comment]
Your call to Close() is not within the ASDURecieveHandler, right? I guess that would cause a deadlock. But calling Cancel() should not help in that case.
I don't think that you are supposed to call Cancel() before Close(), but that might still be a viable workaround.

I'm not sure if the way "running = false" is set in one thread to signal another thread to stop is correct without any synchronization.

**Comment by iman7107** [comment]
Yes. That's right. I call Close() Method in button_Click event, not in ASDURecieverHandler.
So, how can I Close the connection in IEC104 Client? I sometimes need to disconnect my client. 
What solution do you suggest?

**Comment by iman7107** [comment]
Disconnect()? I can't find Disconnect method. 
I can call Dispose() as long as Close() method completes. But the problem is that it does not come out of Close() method.

**Comment by ibekaddour** [comment]
Since the issue is coming from **workerThread.Join();** You can put a condition that will wait for the worker thread to finish within a specified timeout. If the thread does not finish within the timeout, it will close the connection.

**Comment by mzillgith** [comment]
Could it be that the connection thread is stuck in the connection handler? When you are calling the UI in the connection handler then it could be a deadlock because the workerThread.Join is also running in the UI thread.

**Comment by iman7107** [comment]
Hi.
I changed my code and moved my connect and disconnect method into another thread (Background worker) and my problem solved.
Thanks a lot.
