### ISSUE TITLE
document for this libraries 

### ISSUE THREAD

**Issue by ICE2017** [mz-automation/lib60870.NET#4]
do have document for this libraries  thanks.

**Comment by mzillgith** [comment]
Yes. There is the API documentation (https://support.mz-automation.de/doc/lib60870.NET/latest/) and the user guide (https://github.com/mz-automation/lib60870.NET/blob/master/user_guide_dotnet.adoc).

**Comment by ICE2017** [comment]
thanks a lot @mzillgith
