### ISSUE TITLE
Enqueue wait

### ISSUE THREAD

**Issue by redax** [mz-automation/lib60870.NET#5]
https://github.com/mz-automation/lib60870.NET/blob/a40ce3293db3f9e6fa1b18315e76a5e461a41294/lib60870/CS104/Server.cs#L660

Hi!
I am trying to integrate your libray in my code.  I am queuing more than 1000 asdu and I noticed that this method is blocking.
I have commented this "for loop" and the communication is faster and the enqueuing procedure is not blocking anymore.

Am I missing something (I am new to this library)?

Best regards.

**Comment by mzillgith** [comment]
Hi.
Thank you for the hint. The reason for the loop was to be able to send new events faster when the sent queues are empty. But it seems that doesn't work well when there are a lot of messages to be sent. I removed the for loop and calls to send message in the Enqueue function.
