### ISSUE TITLE
Reading data 

### ISSUE THREAD

**Issue by kemas88** [mz-automation/lib60870.NET#8]
Hello,,

I have problem to read several data on C#. In example i want to read "single point information", "measured scale" then show the result on "Label or textboxt" simultanously and continuesly. Is it possible?
I tried to copy paste the code from lib60870.NET/examples/cs104-client1/ then change the code from "console.writeln" to "Label.text or textboxt.text" but it doesn't work. =)

I am new comer on C# programming, so please feel free to explain.

best regards,
kemas

**Comment by mzillgith** [comment]
This is a question on GUI programming in general and not related to this library. I am sure you can find the answer with google or stackoverflow.
